- name: Installing graphite
  hosts: all
  become: yes
  become_method: sudo

  tasks:
    - name: Install Graphite packages
      apt: "name={{item}} state=present"
      with_items:
        - graphite-web
        - graphite-carbon
