- name: Installing kafka
  hosts: all
  gather_facts: yes

  vars:
    - kafka_version: "{{ ansible_env.TMUX_VERSION | default('0.8.2.2') }}"

    - name: Update system package repository
      sudo: true
      command: "{{item}}"
      with_items:
        - apt-get update
        - apt-get install build-essential git git-dev default-jre default-jdk maven

    - name: Download and extract kafka
      command: "{{item}}"
      with_items:
        - "wget 'http://apache.cs.utah.edu/kafka/{{ kafka_version }}/kafka_2.10-{{ kafka_version }}.tgz'"
        - "tar -xzf kafka_2.10-{{ kafka_version }}.tgz"
        - "mv kafka_2.10-{{ kafka_version }} kafka"

    - name: Post install setup
      command: "{{item}}"
      with_items:
        - cp
