- name: Installing python 3
  hosts: all
  gather_facts: yes

    - name: Update system package repository
      sudo: true
      command: "{{item}}"
      tags: [packages]
      with_items:
        - apt-get update
        - apt-get install -y software-properties-common python-software-properties
        - add-apt-repository -y ppa:fkrull/deadsnakes
        - apt-get update

    - name: Install Ubuntu packages and datapipe dependencies
      sudo: true
      apt: pkg="{{item}}" state=installed update_cache=true
      tags: [packages]
      with_items:
        - build-essential
        - checkinstall
        - libreadline-gplv2-dev
        - libssl-dev
        - libsqlite3-dev
        - tk-dev
        - libgdbm-dev
        - libc6-dev
        - libbz2-dev
        - git
        - libffi-dev
        - libpq-dev
        - python3.5
        - python3.5-dev
        - libncurses5-dev
        - libncursesw5-dev
        - python3.5-gdbm

    - name: Finalize package installation
      sudo: true
      command: "{{item}}"
      tags: [packages]
      when: packages_installed
      with_items:
        - mv /usr/bin/python3 /usr/bin/python3.old
        - ln -s /usr/bin/python3.5 /usr/bin/python3
        - wget https://bootstrap.pypa.io/get-pip.py
        - python3 get-pip.py
        - python3 -m pip install -U pip
